--- 
title: "Computational Phylogenetics: A Hands-on Tutorial"
author: "Mingyu Yuan"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [ref.bib]
biblio-style: apalike
link-citations: yes
colorlinks: yes
github-repo: https://github.com/zimine/chl
description: "This notebook includes a brief introductory to computational phylogenetics and a tutorial of implementing related methods."
---

# Welcome{-}

`r emo::ji("wave")` Hi! This tutorial is largely inspired by [Prof. Andrew Garrett](http://linguistics.berkeley.edu/~garrett/)'s class (*LING230 Advanced Historical Linguistics, Spring 2022*) and [Edwin Ko](http://eddersko.com/)'s past and current work on computational phylogenetics. I am deeply grateful to both of them. All errors are my own. 

The purposes of this tutorial are three-fold. First, to briefly summarize the past and present of computational phylogenetics, providing an overview of computatioanl methods applied in this line of research. Second,  to introduce Bayesian phylogenetics and relevant details, including trait selection, data format and coding scheme, and existing software and packages. Lastly, to give a step-by-step tutorial of implementing Bayesian-MCMC method in command lines with Beastling. @ko2021's analysis of the phylogeny of Siouan is reproduced in Section 3. 

This tutorial does require basic understandings of historical linguistic terms, though wiki links or relevant introductory materials are provided whenever a term is mentioned. This tutorial does not assume or require any programming background though. The .R file used to preprocess data is available in the project repository. Command line basics are introduced in Section 3.

This tutorial is written in Markdown and compiled by Bookdown. It is licensed under the [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/). You can find the full source of this project at [https://github.com/zimine/chl](https://github.com/zimine/chl).

Notes: 

1. I use traits, features, and characters interchangeably throughout the tutorial.
2. The first two sections are highly-condensed summaries of computational phylogenetics. See @nichols2008, @dunn2015, @bowern2018, and @jager2019 for general introductions to computational phylogenetics; also see @hoffmann2021 for a tutorial of implementing Bayesian phylogenetcis in BEAST.